branches:
  except: /^v\d/
language: node_js
node_js: node
after_script: node_modules/.bin/nyc report | npx coveralls
env:
  global:
    - COVERALLS_SERVICE_NAME=travis-pro
    - secure: GvQvkUMU/tZHmSpyCBBA6fbAyrgRlH9FHTvmUXktlN4cEcbyuUxqLyqeemnlD0cCy2IHaD220RIGwtJOKJ4NffjX9JseXtzKXSVjf2L/z8hd7fYbcV4AtftsR0GcDdlgMTGP5IGVjntj5d1akgib4TGEZGSR//1aGa1HscKKu0Gv7lu9Hb5QyYFwRmWaNneaxKg+0bcXIVmeuTGvMA7swOiMyjsjJXIaYbfakL3rRmoT7Jxwm8AObhrJLi6eSe/Payv1KCQJyi0e6I9WXueERt+jIAOPPoEnjLs6DE3vKeu2WbkXwYFDAXMw7+VW88uWDfZoRtR2yitDhCKCWNEo9sbEBFtBK3g/T33m1XXIr5C+HFivjh4EtOuYtne9vIAsz9WZocQtWz2lcd45Lf0scFy1jQN5ekYT6cnuOMqkokCLbmf7IoHsSxXxfl8PfZ+F7ODXk9CgZaKz1Lj0JjfaChTMbwyu6MUN8hy25ZskBDPl9oS7qR9cdz7vQ9VBODWzEuflVR8Scg1HxXq8Do6V+ecXrDvp6gxLLL4lRripvfig6WaJoxzqF3wJ4+SJs9caWU/5BjIHGJqoM2y+LjrqDtu4Ri9a6xJEJBlVmddV4ymxJIcaILkI45xZK0KI9IBqJK5qWL4a1qA/GCLZhF+SsvtwonASMYPqISESMVxwjO8=
